Feature/develop authentication verification UI
Sence1-inc/sp-scholaris-master pull request #40
Opened 2024-03-12 07:17 UTC by christian-barrios995

Name: "Develop Authentication and Verification Pages UI"
About: 
- Design and implement UI pages for user authentication and email verification.
- Include pages for signing up, signing in, and verifying email.
- Implement user-friendly interfaces with appropriate form fields and error handling.
Labels: feature
notion link: [Develop Authentication and Verification Pages UI](https://www.notion.so/PRO-MVP-Develop-Authentication-and-Verification-Pages-UI-b9d423b500f345ac9e1a00327f401ad0?pvs=4)

Important things to check:
reusability and features

---
Feature Description
- Created authentication UI
- Created Verification UI

---
Steps to Reproduce the Feature

- Sign-in Page: localhost:3000/sign-in
- Sign-up page: localhost: 3000/sign-up
- Verify password: localhost: 3000/verify-email

---
Expected Behavior

- Page loads normally
- Page Layout shows responsiveness

---
Test Environment
Browser: [e.g. Chrome, Safarri, Firefox]
Test Scenarios:

- [ ] Did the Test Feature Pass?

- [ ] Did you check the features on different browsers?

2024-03-12 07:21 UTC, christian-barrios995 commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +  const [borderColorValidation, setBorderColorValidation] = useState(
Ate Roan, how should the invalid input look like?

2024-03-12 07:22 UTC, christian-barrios995 commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +  function handleCredentials(){
Ate Roan. What more error validation should be added in the sign in?

2024-03-12 07:24 UTC, christian-barrios995 commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +        variant="contained"
Ate Roan. Should sign-in with google be removed? I forgot what we've talked before and could not find the notion notes.

2024-03-12 07:28 UTC, christian-barrios995 commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +
@sence1roandayne Ate Roan, what else should be added or removed?

2024-03-12 08:22 UTC, sence1roandayne requested changes

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/App.tsx
> +        <Route path='/Sign-up' element={<SignUpPage/>}/>
make the /Sign-up small caps

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +                    backgroundColor: '#F3F3F3',
Let's make this white nalang. Like lahat ng bg color ng textfield components ay white nalang. dark bg color is commonly used for defaults pala and white sa mga pwedeng iedit ng users.

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +        variant="contained"
Yes please remove it for now. We will only use email-password sign in and sign up

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +  const [borderColorValidation, setBorderColorValidation] = useState(
Let's use Snackbar component for all success and error messages

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +                placeholder='Input your email'
Update placeholder

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +                placeholder='Input your email'
Update placeholder

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +                label="Password"
Make this Confirm Password

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +  function handleSignUp(){
Please double check this function. I'm not getting any error messages. I think hindi kasi naka wrap sa else yung`navigate('/verify-email')`

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +    //const isPasswordValid what is the condition for the password to be valid?
Min. 8 nalang

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignUpPage/SignUpPage.tsx
> +
Also check if email and pw are present. Add "required" FE validation

2024-03-12 08:22 UTC, sence1roandayne commented on frontend/src/containers/SignInPage/SignInPage.tsx
> +        <Link
For links,
```
import { Link as MuiLink } from '@mui/material'
import { Link as RouterLink } from 'react-router-dom'

return (
   <MuiLink
          component={RouterLink}
          to="/sign-up"
          underline="none"
          variant="body1"
          sx={{
            cursor: 'pointer',
            fontSize: '16px',
            color: '#767676',
            marginBottom: '10px',
            textAlign: 'start',
          }}
        >
          No account yet? Sign-up here
     </MuiLink>
)
```

2024-03-14 06:17 UTC, sence1roandayne commented
@christian-barrios995 Please pull latest develop

2024-03-14 07:14 UTC, sence1roandayne approved these changes
LGTM

2024-03-14 07:30 UTC, merged