Feature/develop: Provider Profile Page
Sence1-inc/sp-scholaris-master pull request #48
Opened 2024-03-20 08:22 UTC by sence1-greniel

---

Name: "Feature Request ID: 000"
About: _Feature/develop: Provider Profile Page_
Labels: feature
Notion Link: notion_link

---

---

#### Feature Description
 - Create Provider Profile Page (Side Bar Card, Content Card)
 - Integrate Profile Provider Details 
 - Integrate Functionality Subscribe / Unsubscribe Newsletter

---

#### Steps to Reproduce the Feature
- Access Provider Profile Page
- http://localhost:3000/provider/account/1/view-profile
- http://localhost:3000/provider/account/1/account-profile
- http://localhost:3000/provider/account/1/account-security
- http://localhost:3000/provider/account/1/account-settings
- http://localhost:3000/provider/account/1/close-account

http://localhost:3000/provider/account/1 - Results to 404 Page
http://localhost:3000/provider/account - Results to 404 Page
---

#### Expected Behavior
 - Populate data to the contents from the backend.
 - Clicking the sidebar should show correct contents
 - Initial Subscribe/Unsubscribe should work

---

#### Test Environment
 - Browser: [e.g. Chrome, Safarri, Firefox]
 - Test Scenarios:
   - [ ] Did the Test Feature Pass?
   - [ ] Did you check the features on different browsers?

---

#### Additional Details / Context

2024-03-20 09:56 UTC, sence1roandayne requested changes

2024-03-20 09:56 UTC, sence1roandayne commented on frontend/src/containers/ProfilesPage/ProviderProfile/ProviderProfile.tsx
> +}
Can we add all `const theme = {}` related to provider profile page to a different file?

2024-03-20 09:58 UTC, sence1roandayne commented
- [ ] Please add Profile in navigation bar to have access to the profile page. 
- [ ] Make `/view-profile` as the lastRoute's initial data.

2024-03-21 03:57 UTC, sence1-greniel commented on frontend/src/containers/ProfilesPage/ProviderProfile/ProviderProfile.tsx
> +}
@sence1roandayne thank you for checking roan, i've added moved the styles to the styles with the name profileTheme and implemented the styles to all profile secction

2024-03-21 04:14 UTC, sence1roandayne approved these changes
LGTM

2024-03-21 04:15 UTC, merged